filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: doesnotexist
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
releases:
- chart: jx3/jxboot-helmfile-resources
  name: jxboot-helmfile-resources
  values:
  - jx-values.yaml
- chart: doesnotexist/bucketrepo
  name: bucketrepo
  values:
  - jx-values.yaml
- chart: jx3/jx-build-controller
  name: jx-build-controller
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
